# Generated by Django 3.2.7 on 2021-09-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('sal', models.FloatField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
